// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "path";
import { defineConfig, env } from "prisma/config";

// likelive2/ 配下の環境変数ファイルを読み込む
// 優先順位: .env.prod (本番) / .env.dev (開発)
const envDir = resolve(__dirname, "likelive2");
const nodeEnv = process.env.NODE_ENV || "development";

// 環境に応じた.envファイルを読み込む
if (nodeEnv === "production") {
  config({ path: resolve(envDir, ".env.prod") });
} else {
  config({ path: resolve(envDir, ".env.dev") });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
